# fly.toml app configuration file generated for webauthn-demo-tq on 2024-06-14T00:12:59+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'webauthn-demo-tq'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

#[[metrics]]
#  port = 8080
#  path = '/actuator/metrics'
